// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUVgwxFhbyYcfFlLgkWtf--ODaGDxCJCQ',
    appId: '1:26478475884:web:31fc28eb922818d7cbb649',
    messagingSenderId: '26478475884',
    projectId: 'restfulapi-f84f4',
    authDomain: 'restfulapi-f84f4.firebaseapp.com',
    storageBucket: 'restfulapi-f84f4.appspot.com',
    measurementId: 'G-P9W4DTCF7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Nxgp78EFvoQzS90tFlavFOZp5PzuSEU',
    appId: '1:26478475884:android:ceebebba2edb664bcbb649',
    messagingSenderId: '26478475884',
    projectId: 'restfulapi-f84f4',
    storageBucket: 'restfulapi-f84f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxlHtPCpxDaU9p6Iz-o5WxoGPBO45jVEI',
    appId: '1:26478475884:ios:976961cf4715a4e1cbb649',
    messagingSenderId: '26478475884',
    projectId: 'restfulapi-f84f4',
    storageBucket: 'restfulapi-f84f4.appspot.com',
    iosBundleId: 'com.example.restfulapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxlHtPCpxDaU9p6Iz-o5WxoGPBO45jVEI',
    appId: '1:26478475884:ios:ed0b28d6d7d30c5ccbb649',
    messagingSenderId: '26478475884',
    projectId: 'restfulapi-f84f4',
    storageBucket: 'restfulapi-f84f4.appspot.com',
    iosBundleId: 'com.example.restfulapi.RunnerTests',
  );
}
